#!/bin/bash
set -e
set -x

ROOT=$2
CELOS_SERVER=$1

cd $ROOT
# Run integration tests against currently checkout local source on test cluster.
rm -fr celos_deploy
mkdir -p celos_deploy/hdfs

cp src/main/celos/* celos_deploy
cp src/main/oozie/* celos_deploy/hdfs
java -jar ../../celos-ci/build/libs/celos-ci-fat-0.1.jar --testDir src/test/celos-ci --deployDir celos_deploy --workflowName file-copy --mode TEST --target file:///home/celos-ci/target_provided.json --celosServer $CELOS_SERVER

echo You win! All tests OK.
