#!/bin/bash
set -e
set -x

USERNAME=$1
cd $2

ROOT=$(pwd)

cd $ROOT/samples/file-copy-celos-provided

rm -fr celos_deploy
mkdir -p celos_deploy/hdfs

cp src/main/celos/* celos_deploy
cp src/main/oozie/* celos_deploy/hdfs

java -jar ../../celos-ci/build/libs/celos-ci-fat.jar --workflowName file-copy --mode UNDEPLOY --target file://$ROOT/scripts/conf/target_int_test.json --hdfsRoot /user/$USERNAME/celos-int-test

echo You win! All tests OK.
