#!/bin/bash
set -e
set -x

# Run integration tests against currently checkout local source on test cluster.

rm -r -f ~/celos_wrk
mkdir -p ~/celos_wrk/defaults
mkdir -p ~/celos_wrk/state 
mkdir -p ~/celos_wrk/ui 
mkdir -p ~/celos_wrk/workflow 
mkdir -p ~/celos_wrk/logs
cp /home/celos-ci/celos-settings/defaults/test/* ~/celos_wrk/defaults

java -cp '../../celos-server/build/libs/celos-0.1.jar:/etc/hadoop/conf' com.collective.celos.server.Main --defaultsDir ~/celos_wrk/defaults --stateDir ~/celos_wrk/state --uiDir ~/celos_wrk/ui --workflowsDir ~/celos_wrk/workflow --logDir ~/celos_wrk/logs --port 9123