#!/bin/bash
set -e
set -x

# Run integration tests against currently checkout local source on test cluster.

rm -r -f /home/akonopko/celos_wrk
mkdir -p /home/akonopko/celos_wrk/defaults
mkdir -p /home/akonopko/celos_wrk/state 
mkdir -p /home/akonopko/celos_wrk/ui 
mkdir -p /home/akonopko/celos_wrk/workflow 
mkdir -p /home/akonopko/celos_wrk/logs
cp /home/celos-ci/celos-settings/defaults/test/* /home/akonopko/celos_wrk/defaults

java -cp '../../celos-server/build/lib/celos-0.1.jar:/etc/hadoop/conf' com.collective.celos.server.Main --defaultsDir /home/akonopko/celos_wrk/defaults --stateDir /home/akonopko/celos_wrk/state --uiDir /home/akonopko/celos_wrk/ui --workflowsDir /home/akonopko/celos_wrk/workflow --logDir /home/akonopko/celos_wrk/logs --port 9123 