#!/bin/bash
echo stopping containers...
sudo docker ps -a | grep celos | awk '{print $1}' | xargs sudo docker kill
echo deleting containers...
sudo docker ps -a | grep celos | awk '{print $1}' | xargs sudo docker rm