#!/usr/bin/env bash
set -x
set -e

# Prepare deployment dir
DEPLOY_DIR=target/celos_deploy
rm -rf $DEPLOY_DIR
HDFS_DIR=$DEPLOY_DIR/hdfs
mkdir -p $HDFS_DIR/lib
cp -r src/main/celos/* $DEPLOY_DIR
cp -r src/main/oozie/* $HDFS_DIR
cp target/flume-ready-check-1.0.0.jar $HDFS_DIR/lib

# Load celos-cd utility
rm -rf .celos-cd
git clone git@github.com:collectivemedia/celos-cd.git .celos-cd
.celos-cd/deploy-workflow flume-ready-check $DEPLOY_DIR

rm -rf .celos-cd
rm -rf $DEPLOY_DIR