#!/bin/bash
set -e
set -x

cd $1

ROOT=$(pwd)

cd $ROOT/scripts/test/test_files/file-copy

java -jar $ROOT/celos-ci/build/libs/celos-ci.jar --workflowName file-copy --mode undeploy --target file://$ROOT/scripts/test/target_int_test.json --hdfsRoot /user/celos-ci/celos-int-test

echo You win! All tests OK.
