repositories.remote << 'http://repo1.maven.org/maven2/'
repositories.remote << 'https://repository.cloudera.com/artifactory/cloudera-repos/'

HADOOP = transitive('org.apache.hadoop:hadoop-client:jar:2.0.0-cdh4.2.1')


DEPENDENCIES = [
  HADOOP
]


define 'wordcount' do
  project.version = '0.1.0'
  manifest['Main-Class'] = 'com.collective.celos.examples.wordcount.WordCount'

  compile.options.source = '1.6'
  compile.options.target = '1.6'

  compile.with(DEPENDENCIES)
  
  package :jar
end
