---
# Playbook to perform integration testing on Celos
#
# Performs various tests against the servlets.

- hosts: host
  gather_facts: no
  vars:
    service_user: "{{ ansible_ssh_user }}"

  tasks:

  - shell: curl -X POST "http://localhost:{{service_port}}/scheduler"
