#!/bin/bash
if [ $# -eq 1 ]
then
    echo "setting hostname"
    sudo echo "$1.celos.collective-media.net" > /etc/hostname
    sudo echo "" >> /etc/hostname
    sudo hostname -F /etc/hostname
    sudo cp -avf ~/hosts /etc/hosts
else
    echo "setting hostname"
    sudo echo "nn.celos.collective-media.net" > /etc/hostname
    sudo echo "" >> /etc/hostname
    sudo hostname -F /etc/hostname
    sudo cp -avf ~/hosts /etc/hosts
fi
